services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "monitor"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  data:
