services:
  app:
    depends_on:
      - db
    environment:
      ConnectionStrings__Postgres: "Server=db;Port=5432;Database=monitor;User Id=postgres;Password=postgres;"
  db:
    image: postgres
    environment:
      POSTGRES_DB: "monitor"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
