name: Build

on:
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  CONTAINER_IMAGE_REGISTRY: ghcr.io
  CONTAINER_IMAGE_NAME: 2frogsstudio/domain-manager
  CONTAINER_IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3

      - name: Build image
        working-directory: src
        env:
          ContainerImageName: ${{ env.CONTAINER_IMAGE_NAME }}
          ContainerImageTags: ${{ env.CONTAINER_IMAGE_TAG }}
        run: |
          dotnet publish DomainManager --os linux --arch x64 /t:PublishContainer -c Release

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Tag and push image to ghcr.io
        env:
          IMAGE_NAME: ${{ env.CONTAINER_IMAGE_NAME }}
          IMAGE_TAG: ${{ env.CONTAINER_IMAGE_TAG }}
          REGISTRY: ${{ env.CONTAINER_IMAGE_REGISTRY }}
        run: |
          docker tag $IMAGE_NAME:$IMAGE_TAG $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
          docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
