name: Hosting

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_run:
    workflows: [ Build ]
    types: [ completed ]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  HOSTING_PATH: .hosting

jobs:
  run-app:
#    restart anyway 
#    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Pull image
        working-directory: ${{ env.HOSTING_PATH }}
        run: |
          docker-compose pull

      - name: Run app
        working-directory: ${{ env.HOSTING_PATH }}
        env:
          BOT__TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          docker-compose up