name: Hosting

on:
  push:
    paths:
      - .github/workflows/hosting.yaml
    branches:
      - main
  schedule:
    - cron: '0 */4 * * *'
  workflow_run:
    workflows: [ Build ]
    types: [ completed ]
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

env:
  HOSTING_PATH: .hosting

jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create .env file
        working-directory: ${{ env.HOSTING_PATH }}
        run: |
          cat <<EOT > .env
          DOTNET_ENVIRONMENT=Production
          Bot__Token=${{ secrets.BOT_TOKEN }}
          ConnectionStrings__Postgres=${{secrets.SUPABASE_CONNECTION_STRING }}
          SENTRY_DSN=${{ secrets.SENTRY_DSN }}
          EOT

      - name: Run app
        working-directory: ${{ env.HOSTING_PATH }}
        run: |
          docker-compose pull          
          docker-compose up 